DatabaseInfo:
    Host: 127.0.0.1
    Port: "3306"
    Protocol: tcp
    User: webchecker
    Password: P@ssW0rd
    Name: webchecker
ServerInfo:
    LogFile: ./WebChecker.log
    SSLCheck: true
    SSLCheckCycle:
        - 1
        - 3
        - 5
        - 15
        - 30
    MailServerInfo:
        UserName: webchecker
        MailFrom: webchecker@test.com
        MailPassword: P@ssW0rd
        SMTPHost: mail.test.com
        SMTPPort: "25"
        MailSubjectSSL: '[엔클라우드24] (-NAME-) 사이트 인증서 만료 예정 - (-URL-)'
        MailSubjectIssued: '[엔클라우드24] (-NAME-) 사이트 알람 발생 - (-URL-)'
        MailSubjectRecover: '[엔클라우드24] (-NAME-) 사이트 알람 해소 - (-URL-)'
        MailBodySSLFile: ./_html/mailBodySSL.html
        MailBodyIssuedFile: ./_html/mailBodyIssued.html
        MailBodyRecoverFile: ./_html/mailBodyRecover.html
